
version: "3.9"

services:
  php:
    image: php:8.0-apache
    build:
      context: php

    ports:
      - "8080:8080"
    volumes:
      - ./php:/app
      - ./php:/var/www/html

#    depends_on:
#      - db

#  db:
#    image: mysql:8.0
#    restart: always
#    environment:
#      MYSQL_DATABASE: example_db
#      MYSQL_USER: example_user
#      MYSQL_PASSWORD: v3YFLJl37YbsHq4s1p6qzz
#      MYSQL_ROOT_PASSWORD: v3YFLJl37YbsHq4s1p6qzz2
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#
